### ISSUE TITLE
WARNING (MainThread) [custom_components.stateful_scenes.config_flow] 'NoneType' object has no attribute 'icon'

### ISSUE THREAD

**Issue by thorstenhornung1** [hugobloem/stateful_scenes#152]
Good Morning,

after fixing the former bug (thank you so much for that). I was able not able to reinstall stateful scenes

I got this error
WARNING (MainThread) [custom_components.stateful_scenes.config_flow] 'NoneType' object has no attribute 'icon'

I am not really a programmer. However I have done some testing: After downgrading to 1.1.0 it worked stetting up on major releases since 1.2.0 failed.

I was able to re-setup after downgrading to 1.1.0. However Since 1.3.0 I get this error for my configuration:

            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stateful_scenes/helpers.py", line 23, in get_icon_from_entity_id
    icon = er.async_get(entity_id).icon
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'icon'


Thank you very much in advance,
Thorsten

**Comment by hugobloem** [comment]
Apologies for the delay on this. #162 should fix this.

**Comment by thorstenhornung1** [comment]
Dear Hugo,

thanks you so much, this was quick!
Unfortunately I still get an "Unknown error occurred".  - However this time it's the attribute 'lower"

Logger: custom_components.stateful_scenes.config_flow
Quelle: custom_components/stateful_scenes/config_flow.py:96
Integration: Stateful Scenes (Dokumentation, Probleme)
Erstmals aufgetreten: 06:56:30 (7 Vorkommnisse)
Zuletzt protokolliert: 07:04:47

'NoneType' object has no attribute 'lower'


I managed to produce a scenes-test.yaml I managed to get some parts to work by creating a scenes-test.yaml only containing non offending scenes.  Please let me know if you need this.

Merry Christmas,
Thorssten
